[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
base = "dark"
primaryColor = "#5fb8ff"
backgroundColor = "#003047"
secondaryBackgroundColor = "#002033"
textColor = "#ffffff"
font = "sans serif"
